// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzjdX5m3GWir6T_Eh4XsCpQJQjhkHkZG0',
    appId: '1:868296289675:web:fbe7025b7015c727d5138e',
    messagingSenderId: '868296289675',
    projectId: 'wildfire-hack',
    authDomain: 'wildfire-hack.firebaseapp.com',
    storageBucket: 'wildfire-hack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo-jqx073aoQgmOC4cEM03_j8ku83QzKc',
    appId: '1:868296289675:android:f7b86dd06505713bd5138e',
    messagingSenderId: '868296289675',
    projectId: 'wildfire-hack',
    storageBucket: 'wildfire-hack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3D9BvIguTYQ-wKxvFjU_svYZtPTF1HNQ',
    appId: '1:868296289675:ios:a9c64584bd33e4e4d5138e',
    messagingSenderId: '868296289675',
    projectId: 'wildfire-hack',
    storageBucket: 'wildfire-hack.appspot.com',
    iosBundleId: 'com.example.firebird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3D9BvIguTYQ-wKxvFjU_svYZtPTF1HNQ',
    appId: '1:868296289675:ios:eba056448e300872d5138e',
    messagingSenderId: '868296289675',
    projectId: 'wildfire-hack',
    storageBucket: 'wildfire-hack.appspot.com',
    iosBundleId: 'com.example.firebird.RunnerTests',
  );
}
